[project]
name = "ai-example-project"
version = "1.0.0"
description = "Example project"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests==2.31.0",
    "python-dotenv==1.1.0",
]

[tool.uv]
dev-dependencies = []
